using Autodesk.Revit.DB;
using CastorPlugin.Utils;
using Nice3point.Revit.Extensions;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Windows;
using System.Windows.Input;
using System.Windows.Media.Imaging;
using static System.Net.Mime.MediaTypeNames;
using Microsoft.Extensions.Configuration;
using CastorPlugin.Services.DTO;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Linq;

namespace CastorPlugin.Core
{
    /// <summary>
    /// 
    /// </summary>
    /// <autogeneratedoc />
    internal class FamilyExtractor
    {

        private readonly Document _document;
        private readonly IConfiguration _configuration;

        public FamilyExtractor(Document document, IConfiguration configuration)
        {
            _document = document;
            _configuration = configuration;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns> family counts</returns>
        public async Task<int> ExtractFamilies()
        {
            int count = 0;

            FilteredElementCollector collector = new FilteredElementCollector(_document).OfClass(typeof(Family));

            // List of common family categories to exclude
            HashSet<BuiltInCategory> commonCategories = new HashSet<BuiltInCategory>
            {
                BuiltInCategory.OST_Walls,
                BuiltInCategory.OST_Floors,
                BuiltInCategory.OST_Roofs,
                BuiltInCategory.OST_Columns,
                BuiltInCategory.OST_CurtainWallPanels,
                BuiltInCategory.OST_CurtainWallMullions,
                BuiltInCategory.OST_Doors,
                BuiltInCategory.OST_Windows,
                BuiltInCategory.OST_Railings,
                BuiltInCategory.OST_Stairs,
                BuiltInCategory.OST_Ramps,
                BuiltInCategory.OST_ShaftOpening,
                BuiltInCategory.OST_Ceilings
                // Add more common family categories as needed
            };

            foreach (Family family in collector)
            {
                // Check if the family is editable and not in the list of common categories
                if (family.IsEditable && !commonCategories.Contains((BuiltInCategory)family.FamilyCategory.Id.IntegerValue))
                {
                    // Additional check: Ignore families without symbols (types)
                    if (family.GetFamilySymbolIds().Count > 0)
                    {
                        string str = GetFamilyFingerprintInJson(family);

                        Log.Information(str);

                        // Create a nft candidate object 
                        NftWorksCandidates nftCandidate = new NftWorksCandidates
                        {
                            Name = family.Name,
                            Type = 1, // REVIT Family
                            FingerPrintHash = ConvertToSha256(str),
                            FingerPrintInJson = str, // Assign the JSON fingerprint
                            Thumbnail = GetFamilyThumbnail(family)
                        };

                        await PostToServerAsCandidate(nftCandidate);

                        count++;
                    }
                }
            }

            return count;
        }

        private string GetFamilyThumbnail(Family family)
        {
            foreach (ElementId symbolId in family.GetFamilySymbolIds())
            {
                FamilySymbol symbol = _document.GetElement(symbolId) as FamilySymbol;
                if (symbol != null)
                {
                    string thumbnail = ExtractFamilySymbolPreviewThumbnail(symbol);
                    if (!string.IsNullOrEmpty(thumbnail))
                    {
                        return thumbnail; // Return the first valid thumbnail found
                    }
                }
            }

            Log.Warning($"No valid thumbnail found for family: {family.Name}");
            return string.Empty;
        }

        private static async Task PostToServerAsCandidate(NftWorksCandidates nftCandidate)
        {
            // Post the nftCandidate object to server
            try
            {
                string apiUrl = @"http://macbook-pro:3000" + @"/nft-works-candidates"; //_configuration.GetValue<string>("ApiUrl"); // Get API URL from configuration
                string response = await WebServiceBroker.SendPostRequestAsync(apiUrl, nftCandidate);

                if (!string.IsNullOrEmpty(response))
                {
                    // Deserialize the response string to NftWorksCandidates object using System.Text.Json
                    var options = new JsonSerializerOptions
                    {
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase // Add this if your JSON properties use camelCase
                       

                    };
                    var createdCandidate = JsonSerializer.Deserialize<NftWorksCandidates>(response, options);

                    if (createdCandidate != null && !string.IsNullOrEmpty(createdCandidate.FingerPrintHash))
                    {
                        Log.Information($"NFT Works Candidate created successfully. ID: {createdCandidate.FingerPrintHash}");
                    }
                    else
                    {
                        Log.Warning("Failed to parse the server response.");
                    }
                }
                else
                {
                    Log.Error("Failed to create NFT Works Candidate. No response from server.");
                }
            }
            catch (JsonException ex)
            {
                Log.Error($"Error deserializing JSON response: {ex.Message}");
            }
            catch (Exception ex)
            {
                Log.Error($"Error posting NFT Works Candidate to server: {ex.Message}");
            }
        }

        private string ExtractFamilySymbolPreviewThumbnail(FamilySymbol familySymbol)
        {
            System.Drawing.Size size = new System.Drawing.Size(200, 200);
            Bitmap image = familySymbol.GetPreviewImage(size);

            // Convert the bitmap to base64 string
            if (image != null)
            {
                return ImageToBase64(image);
            }
            else
            {
                return string.Empty;
            }
        }

        private string ImageToBase64(Bitmap image)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                image.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                byte[] imageBytes = ms.ToArray();
                return Convert.ToBase64String(imageBytes);
            }
        }

        private string GetFamilyFingerprintInJson(Family family)
        {
            string familyFingerprintInJson = String.Empty;

            // Create a temporary folder within the current assembly directory
            string tempFolder = Path.Combine(Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location), "TempFolder");

            // Create the folder if it doesn't exist
            if (!Directory.Exists(tempFolder))
            {
                Directory.CreateDirectory(tempFolder);
            }


            string outputPath = Path.Combine(tempFolder, $"{family.Name}.rfa");

            Dictionary<string, object> familyFingerPrintDict = new Dictionary<string, object>();


            if (family.IsEditable)
            {

                // RevitApi.Application.OpenDocumentFile(outputPath); 
                // Create a new document
                Document familyDocument = _document.EditFamily(family);

                // make sure it's a real family document
                if (familyDocument.IsFamilyDocument)
                {
                 
                    familyFingerPrintDict = ExtractFamilyParameters(familyDocument);

                    //convert to json string
                    familyFingerprintInJson = JsonSerializer.Serialize(familyFingerPrintDict);
                    Debug.Print(familyFingerprintInJson);


                    //write to file for debug
                    string filePath = Path.Combine(tempFolder, $"{family.Name}.json");
                    using (StreamWriter writer = new StreamWriter(filePath))
                    {
                        writer.WriteLine(familyFingerprintInJson);
                    }


                    ////// get  family symbol from family
                    ////ElementId symbolId = family.GetFamilySymbolIds().FirstOrDefault<ElementId>();
                    ////FamilySymbol symbol = _document.GetElement(symbolId) as FamilySymbol;


                    //bool hasPreviewImage = ExtractFamilySymbolPreviewThumbnail(symbol);
                    //do
                    //{
                    //    ElementId symbolId = family.GetFamilySymbolIds().
                    //    FamilySymbol symbol = _document.GetElement(symbolId) as FamilySymbol;
                    //    hasPreviewImage = ExtractFamilySymbolPreviewThumbnail(symbol);

                    //} while (hasPreviewImage == true);

                    //// Save the family to a temporary file
                    //SaveAsOptions options = new SaveAsOptions();
                    //options.OverwriteExistingFile = true;
                    //familyDocument.SaveAs(outputPath, options);


                }

                // Close the family document
                familyDocument.Close(false);


                // get one family symbol preview image from family, if there are many symbol , get the first one
                IEnumerable<ElementId> symbols = family.GetFamilySymbolIds().AsEnumerable<ElementId>();
                foreach (var symbolId in symbols)
                {
                    FamilySymbol symbol = _document.GetElement(symbolId) as FamilySymbol;

                    // bool hasPreviewImage = ExtractFamilySymbolPreviewThumbnail(symbol);
                    //get only one
                   //  if (hasPreviewImage) break;



                }



            }


            return familyFingerprintInJson;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="familyDocument"></param>
        /// <returns></returns>
        private Dictionary<string, object> ExtractFamilyParameters(Document familyDocument )
        {
            //https://thebuildingcoder.typepad.com/blog/2009/11/family-parameter-value.html

            //init the  basic structure of dictionary 
            var familyFingerPrintDict = DynamicObjectUtil.CreateNestedDictionary(
                    "Asset",
                    new (string Key, object Value)[]
                    {
                        ("AssetType","RevitFamily"),
                        ("AssetName", familyDocument.Title)
                        //("v1", new (string Key, object Value)[]
                        //{
                        //    ("Description","Version 1.0 of family finger print")
                        //})
                    }
           
                );



            FamilyManager mgr = familyDocument.FamilyManager;
            int n = mgr.Parameters.Size;
            Debug.Print( "\nFamily {0} has {1} parameter.", familyDocument.Title, n);

            // store the parameter name and param itself into a dict
            Dictionary<string, FamilyParameter> fps = new Dictionary<string, FamilyParameter>(n);
            foreach (FamilyParameter fp in mgr.Parameters)
            {
                string name = fp.Definition.Name;
                if (!fps.ContainsKey(name))
                {
                    fps.Add(name, fp);
                }
                else
                {
                    // A family can have two or more parameters with the same name.
                    // Adding both to the dictionary will cause an error as keys have to be unique. 
                    // so add a sufix for the duplated parameter name
                    fps.Add(name+"_", fp);
                }
                
            }
            List<string> keys = new List<string>(fps.Keys);
            keys.Sort();


            n = mgr.Types.Size;

            Debug.Print( "Family {0} has {1} type", familyDocument.Title, n);

            foreach (FamilyType t in mgr.Types)
            {
                string typeName = t.Name;

                Debug.Print("  {0}:", typeName);
                foreach (string key in keys)
                {
                    FamilyParameter fp = fps[key];
                    if (t.HasValue(fp))
                    {
                        string value
                          = FamilyParamValueString(t, fp, familyDocument);

                        Debug.Print("    {0} = {1}", key, value);

                        //add to the nested dict
                        DynamicObjectUtil.AddToNestedDictionary(familyFingerPrintDict, "Asset.v1."+ typeName + "." + key, value);

                    }
                }
            }


 


     
            return familyFingerPrintDict;


        }


        private static string FamilyParamValueString(
              FamilyType t,
              FamilyParameter fp,
              Document doc)
        {
            string value = t.AsValueString(fp);
            switch (fp.StorageType)
            {
                case StorageType.Double:
                    value = RealString(
                      (double)t.AsDouble(fp))
                      + " (double)";
                    break;

                case StorageType.ElementId:
                    ElementId id = t.AsElementId(fp);
                    Element e = doc.GetElement( id);
                    value = id.ToString() + " ("
                      + ElementDescription(e) + ")";
                    break;

                case StorageType.Integer:
                    value = t.AsInteger(fp).ToString()
                      + " (int)";
                    break;

                case StorageType.String:
                    value = "'" + t.AsString(fp)
                      + "' (string)";
                    break;
            }
            return value;
        }


        // 创建嵌套字典的辅助方法
        private static Dictionary<string, object> CreateNestedDictionary(
                string key, 
                params (string Key, object Value)[] keyValuePairs
            )
        {
            var dictionary = new Dictionary<string, object>();
            foreach (var (Key, Value) in keyValuePairs)
            {
                if (Value is (string, object)[] nestedKeyValuePairs)
                {
                    // 递归创建嵌套字典
                    dictionary[Key] = CreateNestedDictionary(Key, nestedKeyValuePairs);
                }
                else
                {
                    // 添加键值对到当前字典
                    dictionary[Key] = Value;
                }
            }
            return dictionary;
        }
    

    private static BitmapSource ConvertBitmapToBitmapSource(Bitmap bmp)
        {
            return System.Windows.Interop.Imaging
              .CreateBitmapSourceFromHBitmap(
                bmp.GetHbitmap(),
                IntPtr.Zero,
                Int32Rect.Empty,
                BitmapSizeOptions.FromEmptyOptions());
        }

        private static string ElementDescription(Element e)
        {
            if (null == e)
            {
                return "<null>";
            }
            // for a wall, the element name equals the
            // wall type name, which is equivalent to the
            // family name ...
            FamilyInstance fi = e as FamilyInstance;
            string fn = (null == fi)
              ? string.Empty
              : fi.Symbol.Family.Name + " ";

            string cn = (null == e.Category)
              ? e.GetType().Name
              : e.Category.Name;

            return string.Format("{0} {1}<{2} {3}>",
              cn, fn, e.Id.ToString(), e.Name);
        }

        private static string RealString(double a)
        {
            return a.ToString("0.##");
        }

        private string ConvertToSha256(string input)
        {
            using (SHA256 sha256 = SHA256.Create())
            {
                byte[] inputBytes = Encoding.UTF8.GetBytes(input);
                byte[] hashBytes = sha256.ComputeHash(inputBytes);
                
                StringBuilder builder = new StringBuilder();
                for (int i = 0; i < hashBytes.Length; i++)
                {
                    builder.Append(hashBytes[i].ToString("x2"));
                }
                return builder.ToString();
            }
        }

    }
}
